export const data = [
    {
        id: 1,
        name: 'image1',
        title: 'Increasing Prosperity With Positive Thinking',
        urlToImage: 'src/assets/images/strategies/img1.png',
        tags: ['Art', 'Design'],
        content: 'Knowing yourself is the first, and a very critical step in the process of planning your future. How can you figure out what you want to do with your life if you don’t know: What am I going to do with the  rest of my life? What is my dream job? What do I enjoy doing? What’s my passion? What kind of career fits my personality?',
        date: '14.03.2024',
    },
    {
        id: 2,
        name: 'image2',
        title: 'Motivation Is The First Step To Success',
        urlToImage: 'src/assets/images/strategies/img2.png',
        tags: ['Culture'],
        content: 'Knowing yourself is the first, and a very critical step in the process of planning your future. How can you figure out what you want to do with your life if you don’t know: What am I going to do with the  rest of my life? What is my dream job? What do I enjoy doing? What’s my passion? What kind of career fits my personality?',
        date: '14.03.2024',
    },
    {
        id: 3,
        name: 'image3',
        title: 'Success Steps For Your Personal Or Business Life',
        urlToImage: 'src/assets/images/strategies/img3.png',
        tags: ['Culture', 'Design', 'Art'],
        content: 'Knowing yourself is the first, and a very critical step in the process of planning your future. How can you figure out what you want to do with your life if you don’t know: What am I going to do with the  rest of my life? What is my dream job? What do I enjoy doing? What’s my passion? What kind of career fits my personality?',
        date: '14.03.2024',
    },
    {
        id: 4,
        name: 'image4',
        title: 'Success Steps For Your Personal Or Business Life',
        urlToImage: 'src/assets/images/strategies/img4.png',
        tags: ['Culture', 'Design', 'Art'],
        content: 'Knowing yourself is the first, and a very critical step in the process of planning your future. How can you figure out what you want to do with your life if you don’t know: What am I going to do with the  rest of my life? What is my dream job? What do I enjoy doing? What’s my passion? What kind of career fits my personality?',
        date: '14.03.2024',
    },
    {
        id: 5,
        name: 'image5',
        title: 'Increasing Prosperity With Positive Thinking',
        urlToImage: 'src/assets/images/strategies/img5.png',
        tags: ['Design'],
        content: 'Knowing yourself is the first, and a very critical step in the process of planning your future. How can you figure out what you want to do with your life if you don’t know: What am I going to do with the  rest of my life? What is my dream job? What do I enjoy doing? What’s my passion? What kind of career fits my personality?',
        date: '14.03.2024',
    },
    {
        id: 6,
        name: 'image6',
        title: 'Increasing Prosperity With Positive Thinking',
        urlToImage: 'src/assets/images/strategies/img1.png',
        tags: ['Art', 'Design'],
        content: 'Knowing yourself is the first, and a very critical step in the process of planning your future. How can you figure out what you want to do with your life if you don’t know: What am I going to do with the  rest of my life? What is my dream job? What do I enjoy doing? What’s my passion? What kind of career fits my personality?',
        date: '14.03.2024',
    },
    {
        id: 7,
        name: 'image7',
        title: 'Motivation Is The First Step To Success',
        urlToImage: 'src/assets/images/strategies/img2.png',
        tags: ['Culture'],
        content: 'Knowing yourself is the first, and a very critical step in the process of planning your future. How can you figure out what you want to do with your life if you don’t know: What am I going to do with the  rest of my life? What is my dream job? What do I enjoy doing? What’s my passion? What kind of career fits my personality?',
        date: '14.03.2024',
    },
    {
        id: 8,
        name: 'image8',
        title: 'Success Steps For Your Personal Or Business Life',
        urlToImage: 'src/assets/images/strategies/img3.png',
        tags: ['Culture', 'Design', 'Art'],
        content: 'Knowing yourself is the first, and a very critical step in the process of planning your future. How can you figure out what you want to do with your life if you don’t know: What am I going to do with the  rest of my life? What is my dream job? What do I enjoy doing? What’s my passion? What kind of career fits my personality?',
        date: '14.03.2024',
    },
]


/* {
    id: 'data9',
    title: 'Success Steps For Your Personal Or Business Life',
    urlToImage: 'src/assets/images/strategies/img4.png',
    tags: ['Culture', 'Design', 'Art'],
    content: 'Knowing yourself is the first, and a very critical step in the process of planning your future. How can you figure out what you want to do with your life if you don’t know: What am I going to do with the  rest of my life? What is my dream job? What do I enjoy doing? What’s my passion? What kind of career fits my personality?',
    date: '14.03.2024',
}, */